# Tutorial for pytorch

In [1]:
# To install
# conda install pytorch torchvision torchaudio cpuonly -c pytorch
import torch
import numpy as np

---

## Tensor Basics

In pytorch everything is tensor (similar to array)

### Tensor creation

In [31]:
# create empty torch 
# scalar
y = torch.empty(1)
print(y)
# 1D
a = torch.empty(3)
print(a)

# 2D
b = torch.rand(2,2)
print(b)

# 3D
c = torch.zeros(2,2,2)
print(c)

# ones
d = torch.ones(2,2)
print(d)

# create from list
e = torch.tensor([2.5,4,6])
print(e)

# with gradient calculation
x = torch.ones(5, requires_grad = True)
print(x)

tensor([-1.7401e-30])
tensor([-4.6819e-02,  3.0630e-41, -3.3776e-02])
tensor([[0.5844, 0.1893],
        [0.3248, 0.2472]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[1., 1.],
        [1., 1.]])
tensor([2.5000, 4.0000, 6.0000])
tensor([1., 1., 1., 1., 1.], requires_grad=True)


### Tensor basic functions

In [22]:
# see datatype
print(a.dtype)

# see size
print(b.size())

# slicing  - first row
print(b[:,0])

# get specific element
print(b[0,0])

# to get actual value in case of 1 element in tensor
print(b[0,0].item())

torch.float32
torch.Size([2, 2])
tensor([0.7329, 0.9406])
tensor(0.7329)
0.7329225540161133


### Tensor arithmetic function

In [23]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

# adding 
z = x + y
print(z)

z = torch.add(x,y)
print(z)

# inplace addition
y.add_(x)
print(y)

tensor([[0.3713, 0.6690],
        [0.7962, 0.4409]])
tensor([[0.4985, 0.3516],
        [0.0425, 0.4392]])
tensor([[0.8698, 1.0206],
        [0.8387, 0.8801]])
tensor([[0.8698, 1.0206],
        [0.8387, 0.8801]])
tensor([[0.8698, 1.0206],
        [0.8387, 0.8801]])


 Function with ****_**** does inplace modification.

### Reshaping tensor

In [24]:
x = torch.rand(4,4)
print(x)
# make 1D
y = x.view(16)
print(y)

# don't mention dimension
y = x.view(-1,8)
print(y)

tensor([[0.1063, 0.5462, 0.6963, 0.0658],
        [0.8511, 0.1301, 0.3168, 0.7867],
        [0.0139, 0.1199, 0.3417, 0.1384],
        [0.1743, 0.2331, 0.5830, 0.1837]])
tensor([0.1063, 0.5462, 0.6963, 0.0658, 0.8511, 0.1301, 0.3168, 0.7867, 0.0139,
        0.1199, 0.3417, 0.1384, 0.1743, 0.2331, 0.5830, 0.1837])
tensor([[0.1063, 0.5462, 0.6963, 0.0658, 0.8511, 0.1301, 0.3168, 0.7867],
        [0.0139, 0.1199, 0.3417, 0.1384, 0.1743, 0.2331, 0.5830, 0.1837]])


---


### Tensor and numpy

Create numpy array from tensor

In [26]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
# this is sharing same memory in cpu

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


Create tensor from numpy

In [29]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


---

## Autograd package 

This is used to calculate gradient

### Track gradient

In [3]:
x = torch.randn(3, requires_grad = True)
x

tensor([-1.5533, -2.3376,  0.0516], requires_grad=True)

***requires_grad*** helps pytorch to maintain computation graph for gradient.

To calculate gradient let the function be a ***Add*** a scalar to the tensor.

In [4]:
y = x +2 
y

tensor([ 0.4467, -0.3376,  2.0516], grad_fn=<AddBackward0>)

**grad_fn** is the gradient function 

In [5]:
z = y*y*2
z

tensor([0.3991, 0.2279, 8.4183], grad_fn=<MulBackward0>)

### Calculate gradient of a scalar

In [6]:
z = z.mean()
z

tensor(3.0151, grad_fn=<MeanBackward0>)

To calculate the gradient

In [7]:
z.backward() # dz/dx
print(x.grad) # if z is scalar

tensor([ 0.5956, -0.4501,  2.7355])


### Calculate gradient of a vector

In [8]:
y

tensor([ 0.4467, -0.3376,  2.0516], grad_fn=<AddBackward0>)

In [10]:
# we need to have a vector 
v = torch.tensor([0.1,1.0,00.1], dtype=torch.float32)
y.backward(v)
print(x.grad)

tensor([0.6956, 0.5499, 2.8355])


### Untracking gradients

In [11]:
# Option 1
x.requires_grad_(False)
x # removes the grad attribute

tensor([-1.5533, -2.3376,  0.0516])

In [12]:
# Option 2
x = torch.randn(3, requires_grad = True)
y = x.detach() # creates new tensor which does not track
x,y

(tensor([ 1.3655, -0.2136, -2.5621], requires_grad=True),
 tensor([ 1.3655, -0.2136, -2.5621]))

In [14]:
# Option 3
x = torch.randn(3, requires_grad = True)
with torch.no_grad():
    y = x+2
    print(y)

tensor([3.3558, 3.0985, 2.1611])


### Functioning of backward() and grad

In [15]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(2):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    # all weights are summed up
  
    

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])


In [16]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(2):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()
    # so for proper calculation, we need to make the grads zero

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
