# Tutorial for pytorch

In [25]:
# To install
# conda install pytorch torchvision torchaudio cpuonly -c pytorch
import torch
import numpy as np

---

## Tensor Basics

In pytorch everything is tensor (similar to array)

### Tensor creation

In [31]:
# create empty torch 
# scalar
y = torch.empty(1)
print(y)
# 1D
a = torch.empty(3)
print(a)

# 2D
b = torch.rand(2,2)
print(b)

# 3D
c = torch.zeros(2,2,2)
print(c)

# ones
d = torch.ones(2,2)
print(d)

# create from list
e = torch.tensor([2.5,4,6])
print(e)

# with gradient calculation
x = torch.ones(5, requires_grad = True)
print(x)

tensor([-1.7401e-30])
tensor([-4.6819e-02,  3.0630e-41, -3.3776e-02])
tensor([[0.5844, 0.1893],
        [0.3248, 0.2472]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[1., 1.],
        [1., 1.]])
tensor([2.5000, 4.0000, 6.0000])
tensor([1., 1., 1., 1., 1.], requires_grad=True)


### Tensor basic functions

In [22]:
# see datatype
print(a.dtype)

# see size
print(b.size())

# slicing  - first row
print(b[:,0])

# get specific element
print(b[0,0])

# to get actual value in case of 1 element in tensor
print(b[0,0].item())

torch.float32
torch.Size([2, 2])
tensor([0.7329, 0.9406])
tensor(0.7329)
0.7329225540161133


### Tensor arithmetic function

In [23]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

# adding 
z = x + y
print(z)

z = torch.add(x,y)
print(z)

# inplace addition
y.add_(x)
print(y)

tensor([[0.3713, 0.6690],
        [0.7962, 0.4409]])
tensor([[0.4985, 0.3516],
        [0.0425, 0.4392]])
tensor([[0.8698, 1.0206],
        [0.8387, 0.8801]])
tensor([[0.8698, 1.0206],
        [0.8387, 0.8801]])
tensor([[0.8698, 1.0206],
        [0.8387, 0.8801]])


 Function with ****_**** does inplace modification.

### Reshaping tensor

In [24]:
x = torch.rand(4,4)
print(x)
# make 1D
y = x.view(16)
print(y)

# don't mention dimension
y = x.view(-1,8)
print(y)

tensor([[0.1063, 0.5462, 0.6963, 0.0658],
        [0.8511, 0.1301, 0.3168, 0.7867],
        [0.0139, 0.1199, 0.3417, 0.1384],
        [0.1743, 0.2331, 0.5830, 0.1837]])
tensor([0.1063, 0.5462, 0.6963, 0.0658, 0.8511, 0.1301, 0.3168, 0.7867, 0.0139,
        0.1199, 0.3417, 0.1384, 0.1743, 0.2331, 0.5830, 0.1837])
tensor([[0.1063, 0.5462, 0.6963, 0.0658, 0.8511, 0.1301, 0.3168, 0.7867],
        [0.0139, 0.1199, 0.3417, 0.1384, 0.1743, 0.2331, 0.5830, 0.1837]])


---


### Tensor and numpy

Create numpy array from tensor

In [26]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
# this is sharing same memory in cpu

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


Create tensor from numpy

In [29]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


---